Client/Models/ErrorViewModel.cs
namespace Client.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Client/Controllers/FlightController.cs
using Business.Airoport;
using Business.Flight;
using Domain.Dto;
using Domain.Exception;
using Domain.Validators;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;

namespace Client.Controllers
{
    public class FlightController : Controller
    {
        private readonly IAirportService _airportService;
        private readonly IFlightService _flightService;

        public FlightController(IAirportService airportService,
            IFlightService flightService)
        {
            _airportService = airportService;
            _flightService = flightService;
        }

        public async Task<IActionResult> FlightList()
        {
            var model = await _flightService.GetAllAsync();
            return View("List", model);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var lAirports = await _airportService.GetAllAsync();

            var model = new FlightDtoModel
            {
                DepartureAirports = lAirports.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                }).ToList(),
                ArrivalAirports = lAirports.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                }).ToList()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(FlightDtoModel model)
        {
            var validatorResult = new FlightValidator().Validate(model);
            if (!validatorResult.IsValid)
            {
                var lAirports = await _airportService.GetAllAsync();
                foreach (var failure in validatorResult.Errors)
                {
                    ModelState.AddModelError(failure.PropertyName
                        , failure.ErrorMessage);
                }

                model.DepartureAirports = lAirports.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                }).ToList();

                model.ArrivalAirports = lAirports.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                }).ToList();

                return View(model);
            }
            await _flightService.InsertAsync(model);
            return RedirectToAction(nameof(FlightList));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            var model = await _flightService.GetByIdAsync(Id);
            var lAiroports = await _airportService.GetAllAsync();

            model.DepartureAirports = lAiroports.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            }).ToList();

            model.ArrivalAirports = lAiroports.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            }).ToList();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(FlightDtoModel model)
        {
            var validatorResult = new FlightValidator().Validate(model);
            if (!validatorResult.IsValid)
            {
                var lAirports = await _airportService.GetAllAsync();
                foreach (var failure in validatorResult.Errors)
                {
                    ModelState.AddModelError(failure.PropertyName
                        , failure.ErrorMessage);
                }

                model.DepartureAirports = lAirports.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                }).ToList();

                model.ArrivalAirports = lAirports.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                }).ToList();

                return View(model);
            }
            await _flightService.UpdateAsync(model);
            return RedirectToAction(nameof(FlightList));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int pFilghtId)
        {
            await _flightService.DeleteAsync(pFilghtId);
            return RedirectToAction(nameof(FlightList));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(ErrorViewModel model)
        {
            return View(model);
        }
    }
}

Client/Views/Flight/Create.cshtml
@using Domain.Dto;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model FlightDtoModel
@{
}
<form asp-action="Create" asp-controller="Flight">
    <partial name="_CreateOrUpdate" model="Model" />
</form>

Client/Views/Flight/Edit.cshtml
@using Domain.Dto;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model FlightDtoModel
@{
}
<form asp-action="Edit" asp-controller="Flight" asp-method="Post">
    <partial name="_CreateOrUpdate" model="Model" />
</form>

Client/Views/Flight/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Domain.Dto;
@model IList<FlightDtoModel>
@{
    Layout = "_Layout";
}

<a href="/Flight/Create" class="btn btn-info btn-lg">Add New</a>

<table class="table">
    <caption>List of flights</caption>
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Departure Airport</th>
            <th scope="col">Arrival Airport</th>
            <th scope="col">Distance</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.Name</td>
                <td>@item.DepartureAirport</td>
                <td>@item.ArrivalAirport</td>
                <td>@item.Distance</td>
                <td>
                    <a style="display: inline-block;" href="~/Flight/Edit/@item.Id" class="btn btn-success"><i class="fa fa-edit"></i></a>
                    <form style="display: inline-block;" asp-action="Delete" asp-controller="Flight" asp-route-pFilghtId="@item.Id">
                        <button type="submit" onclick="return confirm('Are you sure you want to delete that line?')" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                   </form>
                </td>
            </tr>
        }
    </tbody>
</table>

Client/Views/Flight/_CreateOrUpdate.cshtml
@using Domain.Dto;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model FlightDtoModel
@{
}


<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label class="form-label" asp-for="DepartureAirportId"></label>
            <select class="form-select form-select-lg mb-3" asp-for="DepartureAirportId" asp-items="Model.DepartureAirports">
                <option value="">Please Select</option>
            </select>
            <span asp-validation-for="DepartureAirportId" style="color: red;"></span>
        </div>
            <div class="form-group">
            <label class="form-label" asp-for="ArrivalAirportId"></label>
            <select class="form-select form-select-lg mb-3" asp-for="ArrivalAirportId" asp-items="Model.ArrivalAirports">
                <option value="">Please Select</option>
            </select>
            <span asp-validation-for="ArrivalAirportId" style="color: red;"></span>
        </div>
        <div class="form-group">
            <button class="btn btn-primary mb-3" type="submit">Save</button>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label class="form-label" asp-for="Name"></label>
            <input class="form-control  form-control-lg mb-3" asp-for="Name" />
            <span asp-validation-for="Name" style="color: red;"></span>
        </div>
    </div>
</div>

Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome-4.7.0/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Client.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @*&copy; 2023 - Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>